<a href="https://colab.research.google.com/github/keerthanatcs24-oss/BIS-1WN24CS137/blob/main/bloslab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# ============================================================
# DELIVERY CENTER LOCATION OPTIMIZATION USING PSO
# ============================================================

# ------------------------------------------------------------
# 1. COST / FITNESS FUNCTION
# ------------------------------------------------------------
# x represents the location of the delivery center.
#
# We want to MINIMIZE the delivery cost.
#
# The minimum cost is around x = 6.
# ------------------------------------------------------------

def cost_function(x):

    cost = (x - 6)**2 + 10

    return cost


# ------------------------------------------------------------
# 2. PSO PARAMETERS
# ------------------------------------------------------------

num_particles = 5
max_iterations = 3


w = 0.7
c1 = 1.5
c2 = 1.5


# ------------------------------------------------------------
# 3. INITIALIZE PARTICLES
# ------------------------------------------------------------

# Random locations between 0 and 10 km

positions = np.random.uniform(0, 10, num_particles)


# ------------------------------------------------------------
# 4. INITIAL VELOCITY
# ------------------------------------------------------------

# Random initial movement

velocities = np.random.uniform(-1, 1, num_particles)


# ------------------------------------------------------------
# 5. INITIALIZE pBEST
# ------------------------------------------------------------

# Initially, current position is the personal best

pbest_positions = positions.copy()

pbest_cost = cost_function(pbest_positions)


# ------------------------------------------------------------
# 6. INITIALIZE gBEST
# ------------------------------------------------------------

# Since we are MINIMIZING,
# the smallest cost is the best.

gbest_index = np.argmin(pbest_cost)

gbest_position = pbest_positions[gbest_index]

gbest_cost = pbest_cost[gbest_index]


# ============================================================
# 7. PSO ITERATIONS
# ============================================================

for iteration in range(max_iterations):

    print("\n")
    print("========================================")
    print("ITERATION:", iteration + 1)
    print("========================================")


    # --------------------------------------------------------
    # Calculate current cost
    # --------------------------------------------------------

    current_cost = cost_function(positions)


    print("\nCurrent Positions:")
    print(positions)


    print("\nCurrent Costs:")
    print(current_cost)


    # --------------------------------------------------------
    # UPDATE pBEST
    # --------------------------------------------------------

    for i in range(num_particles):

        # Since we want minimum cost

        if current_cost[i] < pbest_cost[i]:

            pbest_positions[i] = positions[i]

            pbest_cost[i] = current_cost[i]


    print("\npBEST Positions:")
    print(pbest_positions)


    print("\npBEST Costs:")
    print(pbest_cost)


    # --------------------------------------------------------
    # UPDATE gBEST
    # --------------------------------------------------------

    best_index = np.argmin(pbest_cost)


    if pbest_cost[best_index] < gbest_cost:

        gbest_position = pbest_positions[best_index]

        gbest_cost = pbest_cost[best_index]


    print("\ngBEST Position:")
    print(gbest_position)


    print("gBEST Cost:")
    print(gbest_cost)


    # --------------------------------------------------------
    # RANDOM VALUES
    # --------------------------------------------------------

    r1 = np.random.random(num_particles)

    r2 = np.random.random(num_particles)


    # --------------------------------------------------------
    # UPDATE VELOCITY
    # --------------------------------------------------------

    velocities = (

        w * velocities

        + c1 * r1 *
        (pbest_positions - positions)

        + c2 * r2 *
        (gbest_position - positions)

    )


    print("\nNew Velocities:")
    print(velocities)


    # --------------------------------------------------------
    # UPDATE POSITION
    # --------------------------------------------------------

    positions = positions + velocities


    # Keep location between 0 and 10 km

    positions = np.clip(positions, 0, 10)


    print("\nNew Positions:")
    print(positions)


# ============================================================
# 8. FINAL RESULT
# ============================================================

print("\n")
print("========================================")
print("FINAL RESULT")
print("========================================")

print("Best Delivery Center Location:",
      gbest_position, "km")

print("Minimum Delivery Cost:",
      gbest_cost)



ITERATION: 1

Current Positions:
[9.31318522 4.09416936 9.9590912  3.02105382 5.90182581]

Current Costs:
[20.97719628 13.63219043 25.67440309 18.87412033 10.00963817]

pBEST Positions:
[9.31318522 4.09416936 9.9590912  3.02105382 5.90182581]

pBEST Costs:
[20.97719628 13.63219043 25.67440309 18.87412033 10.00963817]

gBEST Position:
5.9018258076234655
gBEST Cost:
10.009638172048785

New Velocities:
[-3.71911045  1.53382305  0.36847123  0.28989899 -0.06157323]

New Positions:
[ 5.59407476  5.62799241 10.          3.31095281  5.84025257]


ITERATION: 2

Current Positions:
[ 5.59407476  5.62799241 10.          3.31095281  5.84025257]

Current Costs:
[10.1647753  10.13838964 26.         17.23097478 10.02551924]

pBEST Positions:
[5.59407476 5.62799241 9.9590912  3.31095281 5.90182581]

pBEST Costs:
[10.1647753  10.13838964 25.67440309 17.23097478 10.00963817]

gBEST Position:
5.9018258076234655
gBEST Cost:
10.009638172048785

New Velocities:
[-2.43206539  1.28555428 -5.88908973  2.07755